<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>$([System.IO.File]::ReadAllText('VERSION.txt').TrimEnd())</Version>
    <TargetFrameworks>netstandard2.1;net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>
     $(NoWarn);
     1573;    <!-- Missing parameter XML tag -->
     1587;    <!-- XML comment is not placed on a valid language element -->
     1591;    <!-- Missing XML comment -->
    </NoWarn>
    <WarningsAsErrors>
      $(WarningAsErrors);
      CS8785;
    </WarningsAsErrors>
    <RestoreUseLegacyDependencyResolver>true</RestoreUseLegacyDependencyResolver>
    <SourceRoot>./src</SourceRoot>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>
  <ItemGroup Label="Roslyn">
    <Compile Remove="analyzers/**"/>
    <Content Remove="analyzers/**"/>
    <None Remove="analyzers/**"/>
    <ProjectReference Include="./analyzers/Roslyn/MMOR.Roslyn.csproj"/>
    <ProjectReference Include="./analyzers/SourceGen/MMOR.Roslyn.SourceGen.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    <PackageReference Include="MMOR.Roslyn" Version="*" Condition="'$(ContinuousIntegrationBuild)'=='true'" PrivateAssets="true"/>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="third_party/**"/>
    <Content Remove="third_party/**"/>
    <None Remove="third_party/**"/>
    <Compile Remove="**/*.meta"/>
    <Content Remove="**/*.meta"/>
    <None Remove="**/*.meta"/>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.*"/>
    <PackageReference Include="System.Collections.Immutable" Version="10.0.*"/>
    <PackageReference Include="PolySharp" Version="1.16.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="T4.Build" Version="0.2.5"/>
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
    <PackageReference Include="Shim.System.Numerics" Version="6.0.0"/>
    <ProjectReference Include="./third_party/Bcl.CollectionsMarshal/Bcl.CollectionsMarshal/Bcl.CollectionsMarshal.csproj" PrivateAssets="all"/>
    <PackageReference Include="Bcl.CollectionsMarshal" Version="2.1.0.0" Condition="'$(ContinuousIntegrationBuild)'=='true'" PrivateAssets="all"/>
  </ItemGroup>
</Project>
