namespace MMOR.Roslyn {

public partial class OverloadGenerator {
  internal static string GenerateOverloads(MethodModel method) {
    StringBuilder sb = new();
    sb.Append("// <auto-generated/>\n");
    sb.Append("#nullable enable\n");

    // Warning about marking an override method as Obsolete
    // .. without the base implementation being Obsolete
    // I would typically think anyone using this Attribute to already know
    // .. what they are doing when using with Obsolete
    sb.Append("#pragma warning disable CS0809\n");

    for (int i = 0; i < method.usings.Length; ++i) {
      sb.Append("using ").Append(method.usings[i]).Append(';').AppendLine();
    }

    sb.Append("\nnamespace ").Append(method.nspace).Append(" {\n");
    foreach (string type in method.contype) {
      sb.Append(type).Append(" {\n");
    }
    // I wish we have defer

    // TODO: Generate Permutations
    ReadOnlySpan<int> permutations = CartesianCombination(method.parameters);
    int len                        = permutations.Length / method.parameters.Length;
    for (int i = 1; i < len; ++i) {
      // Skip first
      WriteOverload(sb, permutations.Slice(i * method.parameters.Length, method.parameters.Length),
          method);
    }

    foreach (string type in method.contype) {
      sb.Append("}  // ").Append(type).Append('\n');
    }
    sb.Append("}  // ").Append(method.nspace).Append('\n');

    return sb.ToString();
  }

  internal static void WriteOverload(StringBuilder sb, ReadOnlySpan<int> perm, MethodModel method) {
    if (false) {
#pragma warning disable CS0162  // Unreachable code detected
      // NOTE: no satisfactory results for now
      sb.Append($"/// <inheritdoc file=\"{method.asmname}.xml\" path=\"doc/members/member[@name='")
          .Append(method.doc_id)
          .Append("']/*\"/>\n");
      sb.Append("/// <remarks> <b>NOTE:</b> Auto-generated Overload </remarks>\n");
#pragma warning restore CS0162  // Unreachable code detected
    }
    foreach (string attribute in method.attributes) sb.AppendLine(attribute);
    sb.Append(kMethodImpl).Append('\n');

    foreach (string attribute in method.modifiers) sb.Append(attribute).Append(" ");
    sb.Append(method.return_type).Append(" ");
    sb.Append(method.name);
    if (method.type_args.Length > 0) {
      sb.Append('<');
      for (int i = 0; i < method.type_args.Length; ++i) {
        if (i != 0)
          sb.Append(", ");
        sb.Append(method.type_args[i].Item1);
      }
      sb.Append('>');
    }
    sb.Append("(");

    int len = method.parameters.Length;
    for (int i = 0; i < len; ++i) {
      int idx = perm[i];
      if (i != 0)
        sb.Append(", ");

      ParameterModel param = method.parameters[i];
      sb.Append(param.ref_kind);
      foreach (string attribute in param.attributes) sb.Append(attribute).Append(" ");
      if (param.typemaps.Length > 0) {
        sb.Append(param.type.Replace(param.typemaps[idx].from_type, param.typemaps[idx].to_type));
      } else {
        sb.Append(param.type);
      }
      sb.Append(' ').Append(param.name);

      if (param.default_value is not null)
        sb.Append(" = ").Append(param.default_value);
    }
    sb.Append(")");
    if (method.type_args.Length > 0) {
      for (int i = 0; i < method.type_args.Length; ++i) {
        sb.Append(method.type_args[i].Item2);
      }
    }
    sb.Append("{\n");

    // Void cannot compile with return
    if (method.return_type != "void")
      sb.Append("return ");

    sb.Append(method.name).Append("(");
    for (int i = 0; i < len; ++i) {
      int idx = perm[i];
      if (i != 0)
        sb.Append(", ");
      ParameterModel param = method.parameters[i];
      sb.Append(param.ref_kind);
      foreach (string attribute in param.attributes) sb.Append(attribute).Append(" ");
      if (param.typemaps.Length > 0) {
        if (param.typemaps[idx].marshal_method == "")
          sb.Append(param.name);
        else if (param.typemaps[idx].class_lib == "")
          sb.Append(param.name).Append('.').Append(param.typemaps[idx].marshal_method);
        else
          sb.Append(param.typemaps[idx].class_lib)
              .Append('.')
              .Append(param.typemaps[idx].marshal_method)
              .Append('(')
              .Append(param.name)
              .Append(')');
      } else {
        sb.Append(param.name);
      }
    }
    sb.Append(");\n}\n");
  }

  internal static int[] CartesianCombination(ImmutableArray<ParameterModel> parameters) {
    int len           = parameters.Length;
    Span<int> radices = stackalloc int[len];
    int combins       = 1;
    for (int i = 0; i < len; ++i) {
      int radix  = Math.Max(parameters[i].typemaps.Length, 1);
      radices[i] = radix;
      combins *= radix;
    }

    int[] result = new int[len * combins];

    Span<int> counter = stackalloc int[len];
    for (int ci = 0; ci < combins; ++ci) {
      Span<int> vals = result.AsSpan().Slice(ci * len, len);
      for (int i = 0; i < len; ++i) {
        vals[i] = counter[i];
      }
      for (int i = 0; i < len; ++i) {
        if (++counter[i] < radices[i]) {
          break;
        }
        counter[i] = 0;
      }
    }
    return result;
  }
}
}
